version: "3.8"

services:
  phk-battle-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/workspace/PhK-BattleServer
      - ../PhK-Protocol:/workspace/PhK-Protocol:ro
    command: ["sh", "-c", "rm -rf build && python3 tools/check_battle_server.py --build && ./build/phk_battle_server"]

  test:
    profiles:
      - test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/workspace/PhK-BattleServer
      - ../PhK-Protocol:/workspace/PhK-Protocol:ro
    command: ["sh", "-c", "rm -rf build && python3 tools/check_battle_server.py --build"]
